CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    target_user_id BIGINT NOT NULL,  -- 谁接收通知？
    actor_id BIGINT NOT NULL,        -- 谁触发了事件？

    event_type VARCHAR(50) NOT NULL, -- 类型：ARTICLE_LIKED, COMMENT_CREATED...
    resource_id BIGINT NOT NULL,     -- 文章ID 或 评论ID
    resource_slug VARCHAR(255),      -- 文章Slug（方便前端生成链接跳转）

    is_read BOOLEAN NOT NULL DEFAULT FALSE, -- 未读状态
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- 外键约束 (如果用户注销，删除相关通知)
    CONSTRAINT fk_notifications_target FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_actor FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 为查询该用户的未读通知添加索引
CREATE INDEX idx_notifications_target_read ON notifications (target_user_id, is_read);
-- 按时间倒序查所有通知
CREATE INDEX idx_notifications_target_created ON notifications (target_user_id, created_at DESC);